feat: Added modal for editing long variable values
lunary-ai/lunary pull request #380
Opened 2024-06-17 20:38 UTC by 7HR4IZ3

2024-06-18 21:46 UTC, hughcrt requested changes
The button to open the modal should always be visible, even if there's no text in the input. Something similar to this:

![Screenshot 2024-06-18 at 6 40 53 PM](https://github.com/lunary-ai/lunary/assets/24587702/cf92242c-7850-4b6d-b4a4-22b6e3db5d12)

It's not properly positioned too:

![Screenshot 2024-06-18 at 6 42 16 PM](https://github.com/lunary-ai/lunary/assets/24587702/39731ab5-e3a2-40fd-9274-8e089f5e6d89)


It should be on the bottom right, next to the border. Something like this:
![Screenshot 2024-06-18 at 6 45 57 PM](https://github.com/lunary-ai/lunary/assets/24587702/ce7db04d-71aa-42f3-b5cb-d1c6f8aadc3a)

2024-06-18 21:46 UTC, hughcrt commented on packages/frontend/package.json
Why have you added the package `remove`?

2024-06-18 22:22 UTC, hughcrt requested changes

2024-06-18 22:22 UTC, hughcrt commented on packages/frontend/components/SmartViewer/Message.tsx
> -}
You should install the Prettier extension for VSCode and configure it to format on save. You probably have a different formatter, because with prettier there's always a new line at the end of the file. (https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

2024-06-18 22:22 UTC, hughcrt commented on packages/frontend/components/prompts/VariableTextarea.tsx
> +        {/* Modal content */}
this comment is not needed

2024-06-18 22:22 UTC, hughcrt commented on packages/frontend/components/prompts/VariableTextarea.tsx
> +      <div className="variable-textarea">
Prefer using Mantine components instead of native html components. In this case, you can use a https://mantine.dev/core/box/

2024-06-18 22:22 UTC, hughcrt commented on packages/frontend/components/prompts/VariableTextarea.tsx
> +    setPopupButton(!!(e.currentTarget.value.length >= 70))
You don't need to use !! here. The `a >= b` already returns a boolean

2024-06-18 22:22 UTC, hughcrt commented on packages/frontend/styles/globals.css
> +
Do not modify the global css, except to modify defaults styles. We do styling at the compnent level, which is a bit different than the usual css class thing. Mantine components have already a lot of props allowing most styling. Please read about mantine styling here: https://mantine.dev/styles/styles-overview/

It can happen than you have to do complex CSS. In this case, use css modules: https://mantine.dev/styles/css-modules/
But mantine style props (https://mantine.dev/styles/style-props/) plus the `styles` props will get you far.

2024-06-18 23:25 UTC, 7HR4IZ3 commented on packages/frontend/components/SmartViewer/Message.tsx
> +      {editable ? (
This is the only way to dynamically render the html generated by `marked`. It's being used alongside `dompurify` to prevent execution of script tags and other possible vulnerability.

2024-06-18 23:29 UTC, 7HR4IZ3 commented on packages/frontend/components/SmartViewer/Message.tsx
> -}
I didn't setup a formatter yet. I'll do that though

2024-06-18 23:35 UTC, 7HR4IZ3 commented on packages/frontend/components/prompts/VariableTextarea.tsx
> +    setPopupButton(!!(e.currentTarget.value.length >= 70))
I'll fix this.

2024-06-18 23:36 UTC, 7HR4IZ3 commented on packages/frontend/components/prompts/VariableTextarea.tsx
> +      <div className="variable-textarea">
Alright. I'll keep that in mind

2024-06-18 23:41 UTC, 7HR4IZ3 commented on packages/frontend/package.json
Weird, it wasn't intentional

2024-06-18 23:42 UTC, 7HR4IZ3 commented on packages/frontend/styles/globals.css
> +
Alright.

2024-06-19 01:31 UTC, 7HR4IZ3 commented on packages/frontend/components/SmartViewer/Message.tsx
> -    if (!data) return
It's a mistake, it shouldn't be in this branch

2024-06-21 19:13 UTC, hughcrt approved these changes

2024-06-21 19:13 UTC, merged